PERMISSIONS = [
    "PATIENT_VIEW",
    "PATIENT_CREATE",
    "PATIENT_EDIT",
    "PATIENT_DELETE",
    "APPOINTMENT_MANAGE",
    "BILLING_VIEW",
    "BILLING_EDIT",
    "LEDGER_VIEW",
    "USER_MANAGE",
    "BASIC"
]
