"""Seed the dental ICD code set (AUX-4) from the legacy Denticon ICD list.

Global catalog (no tenant_id), mirroring procedure_codes. ICD-9/ICD-10/SNOMED
crosswalk columns are blank in the legacy source and left NULL; every row is
seeded ``is_active=False`` (legacy default — the practice activates the codes it
uses via the bulk-status endpoint). Idempotent — skips codes already present.

    python -m scripts.seed_icd_codes
"""

from __future__ import annotations

from sqlalchemy import select

from app.db.models import IcdCode
from app.db.session import SessionLocal

# (code, description) — from the legacy "ICD Codes" screen (ICD-9 dental set).
ICD_CODES: list[tuple[str, str]] = [
    ("327.2", "Organic sleep apnea"),
    ("327.20", "Organic sleep apnea, unspecified"),
    ("327.21", "Primary central sleep apnea"),
    ("327.22", "High altitude periodic breathing"),
    ("327.23", "Obstructive sleep apnea (adult) (pediatric)"),
    ("327.24", "Idiopathic sleep reltd nonobstrctv alveolar hypove"),
    ("327.25", "Congenital central alveolar hypoventilation syndro"),
    ("327.26", "Sleep relatd hypoventilatn/hypoxemia in cond class"),
    ("327.27", "Central sleep apnea in conditions classified elsew"),
    ("327.29", "Other organic sleep apnea"),
    ("520.0", "Anodontia Absence of teeth"),
    ("520.1", "Supernumerary teeth"),
    ("520.2", "Abnormalities of size and form"),
    ("520.3", "Mottled teeth"),
    ("520.4", "Disturbances of tooth formation"),
    ("520.5", "Hereditary disturbances in tooth structure, not el"),
    ("520.6", "Disturbances in tooth eruption"),
    ("520.7", "Teething syndrome"),
    ("520.8", "Other specified disorders of tth devlpmnt/eruption"),
    ("520.9", "Unspecified disorder of tooth development/eruption"),
    ("521.0", "Dental caries"),
    ("521.00", "Dental caries, unspecified"),
    ("521.01", "Dental caries limited to enamel"),
    ("521.02", "Dental caries extending into dentine"),
    ("521.03", "Dental caries extending into pulp"),
    ("521.04", "Arrested dental caries"),
    ("521.05", "Odontoclasia"),
    ("521.06", "Dental caries pit and fissure"),
    ("521.07", "Dental caries of smooth surface"),
    ("521.08", "Dental caries of root surface"),
    ("521.09", "Excessive attrition (approximal wear/occlusal wear"),
    ("521.1", "Excessive attrition (approximal wear/occlusal wear"),
    ("521.10", "Excessive attrition, unspecified"),
    ("521.11", "Excessive attrition, limited to enamel"),
    ("521.12", "Excessive attrition, extending into dentine"),
    ("521.13", "Excessive attrition, extending into pulp"),
    ("521.14", "Excessive attrition, localized"),
    ("521.15", "Excessive attrition, generalized"),
    ("521.2", "Abrasion"),
    ("521.20", "Abrasion, unspecified"),
    ("521.21", "Abrasion, limited to enamel"),
    ("521.22", "Abrasion, extending into dentine"),
    ("521.23", "Abrasion, extending into pulp"),
    ("521.24", "Abrasion, localized"),
    ("521.25", "Abrasion, generalized"),
    ("521.3", "Erosion"),
    ("521.30", "Erosion, unspecified"),
    ("521.31", "Erosion, limited to enamel"),
    ("521.32", "Erosion, extending into dentine"),
    ("521.33", "Erosion, extending into pulp"),
    ("521.34", "Erosion, localized"),
    ("521.35", "Erosion, generalized"),
    ("521.4", "Pathological resorption"),
    ("521.40", "Pathological resorption, unspecified"),
    ("521.41", "Pathological resorption, internal"),
    ("521.42", "Pathological resorption, external"),
    ("521.49", "Other pathological resorption"),
    ("521.5", "Hypercementosis"),
    ("521.6", "Ankylosis of teeth"),
    ("521.7", "Intrinsic posteruptive color changes"),
    ("521.8", "Other specified diseases of hard tissues of teeth"),
    ("521.81", "Cracked tooth"),
    ("521.89", "Other specified diseases of hard tissues of teeth"),
    ("521.9", "Unspecified disease of hard tissues of teeth"),
    ("522.0", "Pulpitis"),
    ("522.1", "Necrosis of the pulp"),
    ("522.2", "Pulp degeneration"),
    ("522.3", "Abnormal hard tissue formation in pulp"),
    ("522.4", "Acute apical periodontitis of pulpal origin"),
    ("522.5", "Periapical abscess without sinus"),
    ("522.6", "Chronic apical periodontitis"),
    ("522.7", "Periapical abscess with sinus"),
    ("522.8", "Radicular cyst"),
    ("522.9", "Other/unspcified diseases of pulp/periapical tissu"),
    ("523.0", "Acute gingivitis"),
    ("523.00", "Acute gingivitis, plaque induced"),
    ("523.01", "Acute gingivitis, non-plaque induced"),
    ("523.1", "Chronic gingivitis"),
    ("523.10", "Chronic gingivitis, plaque induced"),
    ("523.11", "Chronic gingivitis, non-plaque induced"),
    ("523.2", "Gingival recession"),
    ("523.20", "Gingival recession, unspecified"),
    ("523.21", "Gingival recession, minimal"),
    ("523.22", "Gingival recession, moderate"),
    ("523.23", "Gingival recession, severe"),
    ("523.24", "Gingival recession, localized"),
    ("523.25", "Gingival recession, generalized"),
    ("523.3", "Aggressive and acute periodontitis"),
    ("523.30", "Aggressive periodontitis, unspecified"),
    ("523.31", "Aggressive periodontitis, localized"),
    ("523.32", "Aggressive periodontitis, generalized"),
    ("523.33", "Acute periodontitis"),
    ("523.4", "Chronic periodontitis"),
    ("523.40", "Chronic periodontitis, unspecified"),
    ("523.41", "Chronic periodontitis, localized"),
    ("523.42", "Chronic periodontitis, generalized"),
    ("523.5", "Periodontosis"),
    ("523.6", "Accretions on teeth"),
    ("523.8", "Other specified periodontal diseases"),
    ("523.9", "Unspecified gingival and periodontal disease"),
    ("524.0", "Major anomalies of jaw size"),
    ("524.00", "Unspecified anomaly"),
    ("524.01", "Maxillary hyperplasia"),
    ("524.02", "Mandibular hyperplasia"),
    ("524.03", "Maxillary hypoplasia"),
    ("524.04", "Mandibular hypoplasia"),
    ("524.05", "Macrogenia"),
    ("524.06", "Microgenia"),
    ("524.07", "Excessive tuberosity of jaw"),
    ("524.09", "Other specified anomaly"),
    ("524.1", "Anomalies of relationship of jaw to cranial base"),
    ("524.10", "Unspecified anomaly"),
    ("524.11", "Maxillary asymmetry"),
    ("524.12", "Other jaw asymmetry"),
    ("524.19", "Other specified anomaly"),
    ("524.2", "Anomalies of dental arch relationship"),
    ("524.20", "Unspecified anomaly of dental arch relationship"),
    ("524.21", "Malocclusion, Angle's class I"),
    ("524.22", "Malocclusion, Angle's class II"),
    ("524.23", "Malocclusion, Angle's class III"),
    ("524.24", "Open anterior occlusal relationship"),
    ("524.25", "Open posterior occlusal relationship"),
    ("524.26", "Excessive horizontal overlap"),
    ("524.27", "Reverse articulation"),
    ("524.28", "Anomalies of interarch distance"),
    ("524.29", "Other anomalies of dental arch relationship"),
    ("524.3", "Anomalies of tooth position of fully erupted teeth"),
    ("524.30", "Unspecified anomaly of tooth position"),
    ("524.31", "Crowding of teeth"),
    ("524.32", "Excessive spacing of teeth"),
    ("524.33", "Horizontal displacement of teeth"),
    ("524.34", "Vertical displacement of teeth"),
    ("524.35", "Rotation of tooth/teeth"),
    ("524.36", "Insufficient interocclusal distance of teeth(ridge"),
    ("524.37", "Excessive interocclusal distance of teeth"),
    ("524.39", "Other anomalies of tooth position"),
    ("524.4", "Malocclusion, unspecified"),
    ("524.5", "Dentofacial functional abnormalities"),
    ("524.50", "Dentofacial functional abnormality, unspecified"),
    ("524.51", "Abnormal jaw closure"),
    ("524.52", "Limited mandibular range of motion"),
    ("524.53", "Deviation in opening and closing of the mandible"),
    ("524.54", "Insufficient anterior guidance"),
    ("524.55", "Centric occlusion maximum intercuspation discrepan"),
    ("524.56", "Non-working side interference"),
    ("524.57", "Lack of posterior occlusal support"),
    ("524.59", "Other dentofacial functional abnormalities"),
    ("524.6", "Temporomandibular joint disorders"),
    ("524.60", "Temporomandibular joint disorders, unspecified"),
    ("524.61", "Adhesions and ankylosis (bony or fibrous)"),
    ("524.62", "Arthralgia of temporomandibular joint"),
    ("524.63", "Articular disc disorder (reducing or nonreducing)"),
    ("524.64", "TMJ sounds on opening and/or closing the jaw"),
    ("524.69", "Other specified temporomandibular joint disorders"),
    ("524.7", "Dental alveolar anomalies"),
    ("524.70", "Unspecified alveolar anomaly"),
    ("524.71", "Alveolar maxillary hyperplasia"),
    ("524.72", "Alveolar mandibular hyperplasia"),
    ("524.73", "Alveolar maxillary hypoplasia"),
    ("524.74", "Alveolar mandibular hypoplasia"),
    ("524.75", "Vertical displacement of alveolus and teeth"),
    ("524.76", "Occlusal plane deviation"),
    ("524.79", "Other specified alveolar anomaly"),
    ("524.8", "Other specified dentofacial anomalies"),
    ("524.81", "Anterior soft tissue impingement"),
    ("524.82", "Posterior soft tissue impingement"),
    ("524.89", "Other specified dentofacial anomalies"),
    ("524.9", "Unspecified dentofacial anomalies"),
    ("525", "Other diseases/conditions of the tth/supporting st"),
    ("525.0", "Exfoliation of teeth due to systemic causes"),
    ("525.1", "Loss of tth due to trauma/extractn/periodontal dis"),
    ("525.10", "Acquired absence of teeth, unspecified"),
    ("525.11", "Loss of teeth due to trauma"),
    ("525.12", "Loss of teeth due to periodontal disease"),
    ("525.13", "Loss of teeth due to caries"),
    ("525.19", "Other loss of teeth"),
    ("525.2", "Atrophy of edentulous alveolar ridge"),
    ("525.20", "Unspecified atrophy of edentulous alveolar ridge"),
    ("525.21", "Minimal atrophy of the mandible"),
    ("525.22", "Moderate atrophy of the mandible"),
    ("525.23", "Severe atrophy of the mandible"),
    ("525.24", "Minimal atrophy of the maxilla"),
    ("525.25", "Moderate atrophy of the maxilla"),
    ("525.26", "Severe atrophy of the maxilla"),
    ("525.3", "Retained dental root"),
    ("525.4", "Complete edentulism"),
    ("525.40", "Complete edentulism, unspecified"),
    ("525.41", "Complete edentulism, class I"),
    ("525.42", "Complete edentulism, class II"),
    ("525.43", "Complete edentulism, class III"),
    ("525.44", "Complete edentulism, class IV"),
    ("525.5", "Partial edentulism"),
    ("525.50", "Partial edentulism, unspecified"),
    ("525.51", "Partial edentulism, class I"),
    ("525.52", "Partial edentulism, class II"),
    ("525.53", "Partial edentulism, class III"),
    ("525.54", "Partial edentulism, class IV"),
    ("525.6", "Unsatisfactory restoration of tooth"),
    ("525.60", "Unspecified unsatisfactory restoration of tooth"),
    ("525.61", "Open restoration margins"),
    ("525.62", "Unrepairable overhanging of dental restorative mat"),
    ("525.63", "Fractrd dentl restratve material w/o loss of mater"),
    ("525.64", "Fractrd dentl restratve material w loss of materia"),
    ("525.65", "Contour of existing restoration of tooth biologica"),
    ("525.66", "Allergy to existing dental restorative material"),
    ("525.67", "Poor aesthetics of existing restoration"),
    ("525.69", "Other unsatisfactory restoration of existing tooth"),
    ("525.7", "Endosseous dental implant failure"),
    ("525.71", "Osseointegration failure of dental implant"),
    ("525.72", "Post-osseointegration biolgcl failure of dentl imp"),
    ("525.73", "Post-osseointegration mechncl failure of dentl imp"),
    ("525.79", "Other endosseous dental implant failure"),
    ("525.8", "Othr spec disorders of the tth & supportng structu"),
    ("525.9", "Unspecified disorder of the tth & supportng struct"),
    ("526.0", "Developmental odontogenic cysts"),
    ("526.1", "Fissural cysts of jaw"),
    ("526.2", "Other cysts of jaws"),
    ("526.3", "Central giant cell (reparative) granuloma"),
    ("526.4", "Inflammatory conditions"),
    ("526.5", "Alveolitis of jaw"),
    ("526.6", "Periradicular pathology assctd w prev endo treatme"),
    ("526.61", "Perforation of root canal space"),
    ("526.62", "Endodontic overfill"),
    ("526.63", "Endodontic underfill"),
    ("526.69", "Othr periradicular pathology assctd w prev endo tx"),
    ("526.8", "Other specified diseases of the jaws"),
    ("526.81", "Exostosis of jaw"),
    ("526.89", "Other"),
    ("526.9", "Unspecified disease of the jaws"),
    ("527.0", "Atrophy"),
    ("527.1", "Hypertrophy"),
    ("527.2", "Sialoadenitis"),
    ("527.3", "Abscess"),
    ("527.4", "Fistula"),
    ("527.5", "Sialolithiasis"),
    ("527.6", "Mucocele"),
    ("527.7", "Disturbance of salivary secretion"),
    ("527.8", "Other specified diseases of the salivary glands"),
    ("527.9", "Unspecified disease of the salivary glands"),
    ("528.0", "Stomatitis and mucositis (ulcerative)"),
    ("528.00", "Stomatitis and mucositis, unspecified"),
    ("528.01", "Mucositis (ulcerative) due to antineoplastic thera"),
    ("528.02", "Mucositis (ulcerative) due to other drugs"),
    ("528.09", "Other stomatitis and mucositis (ulcerative)"),
    ("528.1", "Cancrum oris"),
    ("528.2", "Oral aphthae"),
    ("528.3", "Cellulitis and abscess"),
    ("528.4", "Cysts"),
    ("528.5", "Diseases of lips"),
    ("528.6", "Leukoplakia of oral mucosa, including tongue"),
    ("528.7", "Othr disturbances of oral epithelium, incld tongue"),
    ("528.71", "Minimal keratinized residual ridge mucosa"),
    ("528.72", "Excessive keratinized residual ridge mucosa"),
    ("528.79", "Other disturbances of oral epithelium, incldg tong"),
    ("528.8", "Oral submucosal fibrosis, including of tongue"),
    ("528.9", "Other & unspecified diseases of the oral soft tiss"),
    ("529.0", "Glossitis"),
    ("529.1", "Geographic tongue"),
    ("529.2", "Median rhomboid glossitis"),
    ("529.3", "Hypertrophy of tongue papillae"),
    ("529.4", "Atrophy of tongue papillae"),
    ("529.5", "Plicated tongue"),
    ("529.6", "Glossodynia"),
    ("529.8", "Other specified conditions of the tongue"),
    ("529.9", "Unspecified condition of the tongue"),
]


def seed(db) -> int:  # noqa: ANN001
    existing = set(db.execute(select(IcdCode.code)).scalars().all())
    added = 0
    for code, description in ICD_CODES:
        if code in existing:
            continue
        db.add(IcdCode(code=code, description=description, is_active=False))
        added += 1
    db.commit()
    return added


def main() -> None:
    db = SessionLocal()
    try:
        n = seed(db)
        print(f"seed_icd_codes: inserted {n} ICD code(s) ({len(ICD_CODES)} in source)")
    finally:
        db.close()


if __name__ == "__main__":
    main()
